version: '3'

services:
  web:
    build: ./web
    depends_on:
      - cdn
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_NAME=redis

  redis:
    image: redis
    
  cdn:
    build: ./cdn
    ports:
      - "5001:5000"
    depends_on:
      - sqlite3
      
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/